import { PortfolioData } from '../types/database';

export const initialPortfolioData: PortfolioData = {
  profile: {
    id: '00000000-0000-0000-0000-000000000001',
    full_name: 'Bilal Ahamed PT',
    headline: 'AI & Data Science | Full Stack Developer',
    bio: 'M.Tech Computer Science and Engineering (AI & Data Science) student at CUSAT with hands-on experience in full-stack development, Generative AI, Machine Learning, cloud technologies, and real-time systems.',
    about: 'M.Tech Computer Science and Engineering (AI & Data Science) student at Cochin University of Science and Technology with hands-on experience in full-stack development, Artificial Intelligence, Machine Learning, cloud technologies, and real-time applications. Skilled in Python, React, Firebase, AWS, and Google Cloud Platform, with experience developing AI-powered applications using OpenAI technologies. Proficient in AI coding tools, prompt engineering, database integration, debugging, testing, deployment, and collaborative software development.',
    email: 'bilalvpm2@gmail.com',
    phone: '+91-7306448145',
    location: 'Kerala, India',
    avatar_url: '',
    about_image_url: '',
    resume_url: '/resume.pdf',
    availability_status: 'Open to Opportunities & Collaborations',
    years_experience: '2+ Years',
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  projects: [
    {
      id: '11111111-1111-1111-1111-111111111101',
      title: 'Smile AI Tutor',
      slug: 'smile-ai-tutor',
      short_description: 'AI-powered personalized learning platform designed to deliver adaptive, student-centric education using Generative AI, NLP, Computer Vision, and adaptive assessment.',
      detailed_description: 'AI-powered personalized learning platform designed to deliver adaptive, student-centric education using Generative AI, NLP, Computer Vision, and adaptive assessment. The platform generates learning modules, evaluates student performance, and dynamically personalizes learning paths with practical modules and handwriting evaluation.',
      category: 'Generative AI / NLP / Full Stack',
      image_url: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
      gallery_images: [
        'https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?auto=format&fit=crop&w=800&q=80'
      ],
      github_url: 'https://github.com/bilalvpm4321',
      live_url: '',
      is_featured: true,
      is_published: true,
      display_order: 1,
      project_date: '2024 - Present',
      metrics: { accuracy: '94%', studentsImpacted: '500+', latency: '<300ms' },
      highlights: [
        'AI-generated adaptive courses & curriculum',
        'Interactive assessments & performance-based progression',
        'Practical learning modules with conversational AI',
        'AI-powered handwritten assignment evaluation with Computer Vision',
        'Personalized learning support & real-time analytics'
      ],
      technologies: [
        { id: 't1', project_id: '11111111-1111-1111-1111-111111111101', name: 'React / Next.js', display_order: 1 },
        { id: 't2', project_id: '11111111-1111-1111-1111-111111111101', name: 'TypeScript', display_order: 2 },
        { id: 't3', project_id: '11111111-1111-1111-1111-111111111101', name: 'FastAPI', display_order: 3 },
        { id: 't4', project_id: '11111111-1111-1111-1111-111111111101', name: 'Python', display_order: 4 },
        { id: 't5', project_id: '11111111-1111-1111-1111-111111111101', name: 'OpenAI GPT Models', display_order: 5 },
        { id: 't6', project_id: '11111111-1111-1111-1111-111111111101', name: 'Computer Vision', display_order: 6 },
        { id: 't7', project_id: '11111111-1111-1111-1111-111111111101', name: 'MongoDB', display_order: 7 },
        { id: 't8', project_id: '11111111-1111-1111-1111-111111111101', name: 'Firebase / Firestore', display_order: 8 },
        { id: 't9', project_id: '11111111-1111-1111-1111-111111111101', name: 'PWA', display_order: 9 },
        { id: 't10', project_id: '11111111-1111-1111-1111-111111111101', name: 'YouTube API', display_order: 10 },
      ],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: '11111111-1111-1111-1111-111111111102',
      title: 'YodhaC.AI',
      slug: 'yodhac-ai',
      short_description: 'Advanced enterprise phishing intelligence and network monitoring platform designed to monitor office systems for malicious URLs and phishing attempts.',
      detailed_description: 'Advanced enterprise phishing intelligence and network monitoring platform designed to monitor office systems for malicious URLs and phishing attempts. When a potentially malicious or phishing URL is detected on an office system, the platform identifies the source system and alerts the administrator with its IP address, allowing security teams to monitor and respond to threats across the office network.',
      category: 'AI / Cybersecurity / ML',
      image_url: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1200&q=80',
      gallery_images: [
        'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80'
      ],
      github_url: 'https://github.com/bilalvpm4321',
      live_url: '',
      is_featured: true,
      is_published: true,
      display_order: 2,
      project_date: '2024',
      metrics: { detectionRate: '98.7%', alertLatency: 'Real-time', classification: 'XGBoost' },
      highlights: [
        'Phishing URL detection & Machine Learning classification',
        'Real-time network packet monitoring & security alerts',
        'Source IP identification & office-wide system monitoring',
        'Automated security response dashboard for system admins'
      ],
      technologies: [
        { id: 't11', project_id: '11111111-1111-1111-1111-111111111102', name: 'React', display_order: 1 },
        { id: 't12', project_id: '11111111-1111-1111-1111-111111111102', name: 'FastAPI', display_order: 2 },
        { id: 't13', project_id: '11111111-1111-1111-1111-111111111102', name: 'Python', display_order: 3 },
        { id: 't14', project_id: '11111111-1111-1111-1111-111111111102', name: 'XGBoost', display_order: 4 },
        { id: 't15', project_id: '11111111-1111-1111-1111-111111111102', name: 'Wireshark', display_order: 5 },
        { id: 't16', project_id: '11111111-1111-1111-1111-111111111102', name: 'Docker', display_order: 6 },
        { id: 't17', project_id: '11111111-1111-1111-1111-111111111102', name: 'Fly.io', display_order: 7 },
      ],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: '11111111-1111-1111-1111-111111111103',
      title: 'Smart Wastebin Management System',
      slug: 'smart-wastebin-management-system',
      short_description: 'ESP32-based smart waste monitoring system using ultrasonic sensors, MQTT, and AWS cloud with predictive fill time ML model.',
      detailed_description: 'Built an ESP32-based smart waste monitoring system using ultrasonic sensors and MQTT. Integrated AWS Lambda and DynamoDB for real-time processing and storage, with a machine learning model to predict bin fill time for optimized waste collection.',
      category: 'IoT / AWS / Machine Learning',
      image_url: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=1200&q=80',
      gallery_images: [],
      github_url: 'https://github.com/bilalvpm4321/Wastebin_management',
      live_url: '',
      is_featured: false,
      is_published: true,
      display_order: 3,
      project_date: '2024',
      metrics: { predictionAccuracy: '92%', cloudLatency: '120ms' },
      highlights: [
        'ESP32 microcontroller integration with ultrasonic sensors',
        'Real-time MQTT telemetry streaming to AWS cloud',
        'AWS Lambda serverless processing and DynamoDB storage',
        'Machine Learning model predicting fill time for smart garbage route optimization'
      ],
      technologies: [
        { id: 't18', project_id: '11111111-1111-1111-1111-111111111103', name: 'ESP32', display_order: 1 },
        { id: 't19', project_id: '11111111-1111-1111-1111-111111111103', name: 'Ultrasonic Sensors', display_order: 2 },
        { id: 't20', project_id: '11111111-1111-1111-1111-111111111103', name: 'MQTT', display_order: 3 },
        { id: 't21', project_id: '11111111-1111-1111-1111-111111111103', name: 'AWS Lambda', display_order: 4 },
        { id: 't22', project_id: '11111111-1111-1111-1111-111111111103', name: 'AWS DynamoDB', display_order: 5 },
        { id: 't23', project_id: '11111111-1111-1111-1111-111111111103', name: 'Machine Learning', display_order: 6 },
      ],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: '11111111-1111-1111-1111-111111111104',
      title: 'Fake News Detection in Malayalam',
      slug: 'fake-news-detection-malayalam',
      short_description: 'Multilingual fake news detection system using NLP and Computer Vision for text, image, and URL authenticity verification.',
      detailed_description: 'Developed a multilingual fake news detection system using NLP and computer vision for text, image, and URL analysis. Implemented image tampering detection, URL credibility checks, reverse search, confidence scoring, and an administrative verification dashboard.',
      category: 'NLP / Computer Vision / AI',
      image_url: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=1200&q=80',
      gallery_images: [],
      github_url: 'https://github.com/bilalvpm4321/Yeah-Fake-news-detection-in-maklayalam',
      live_url: '',
      is_featured: false,
      is_published: true,
      display_order: 4,
      project_date: '2023 - 2024',
      metrics: { languages: 'Malayalam & English', pipeline: 'Multimodal NLP+CV' },
      highlights: [
        'Multimodal NLP for regional Malayalam news corpus analysis',
        'Image tampering and deepfake/manipulation detection',
        'URL credibility checking and automated reverse search',
        'Confidence scoring algorithm with admin moderation dashboard'
      ],
      technologies: [
        { id: 't24', project_id: '11111111-1111-1111-1111-111111111104', name: 'Python', display_order: 1 },
        { id: 't25', project_id: '11111111-1111-1111-1111-111111111104', name: 'NLP', display_order: 2 },
        { id: 't26', project_id: '11111111-1111-1111-1111-111111111104', name: 'Computer Vision', display_order: 3 },
        { id: 't27', project_id: '11111111-1111-1111-1111-111111111104', name: 'Machine Learning', display_order: 4 },
        { id: 't28', project_id: '11111111-1111-1111-1111-111111111104', name: 'Web Scraping', display_order: 5 },
      ],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  skills: [
    // Programming
    { id: 's1', name: 'Python', category: 'Programming', icon: 'python', level: 'Expert', display_order: 1, is_visible: true, created_at: '' },
    { id: 's2', name: 'JavaScript (ES6+)', category: 'Programming', icon: 'javascript', level: 'Advanced', display_order: 2, is_visible: true, created_at: '' },
    { id: 's3', name: 'TypeScript', category: 'Programming', icon: 'typescript', level: 'Advanced', display_order: 3, is_visible: true, created_at: '' },
    { id: 's4', name: 'C / C++', category: 'Programming', icon: 'cpp', level: 'Proficient', display_order: 4, is_visible: true, created_at: '' },
    { id: 's5', name: 'SQL', category: 'Programming', icon: 'sql', level: 'Advanced', display_order: 5, is_visible: true, created_at: '' },

    // AI & Machine Learning
    { id: 's6', name: 'Generative AI', category: 'AI & Machine Learning', icon: 'sparkles', level: 'Advanced', display_order: 1, is_visible: true, created_at: '' },
    { id: 's7', name: 'OpenAI GPT & Prompt Eng.', category: 'AI & Machine Learning', icon: 'bot', level: 'Advanced', display_order: 2, is_visible: true, created_at: '' },
    { id: 's8', name: 'Machine Learning', category: 'AI & Machine Learning', icon: 'brain', level: 'Advanced', display_order: 3, is_visible: true, created_at: '' },
    { id: 's9', name: 'Deep Learning', category: 'AI & Machine Learning', icon: 'cpu', level: 'Proficient', display_order: 4, is_visible: true, created_at: '' },
    { id: 's10', name: 'Natural Language Processing', category: 'AI & Machine Learning', icon: 'file-text', level: 'Advanced', display_order: 5, is_visible: true, created_at: '' },
    { id: 's11', name: 'Computer Vision', category: 'AI & Machine Learning', icon: 'eye', level: 'Proficient', display_order: 6, is_visible: true, created_at: '' },
    { id: 's12', name: 'XGBoost & Scikit-Learn', category: 'AI & Machine Learning', icon: 'activity', level: 'Advanced', display_order: 7, is_visible: true, created_at: '' },

    // Frontend
    { id: 's13', name: 'React.js', category: 'Frontend', icon: 'atom', level: 'Advanced', display_order: 1, is_visible: true, created_at: '' },
    { id: 's14', name: 'Next.js', category: 'Frontend', icon: 'layers', level: 'Advanced', display_order: 2, is_visible: true, created_at: '' },
    { id: 's15', name: 'Tailwind CSS', category: 'Frontend', icon: 'wind', level: 'Expert', display_order: 3, is_visible: true, created_at: '' },
    { id: 's16', name: 'HTML5 & Modern CSS3', category: 'Frontend', icon: 'code', level: 'Expert', display_order: 4, is_visible: true, created_at: '' },
    { id: 's17', name: 'Vite & PWA', category: 'Frontend', icon: 'zap', level: 'Advanced', display_order: 5, is_visible: true, created_at: '' },
    { id: 's18', name: 'Framer Motion', category: 'Frontend', icon: 'play', level: 'Advanced', display_order: 6, is_visible: true, created_at: '' },

    // Backend & Cloud
    { id: 's19', name: 'FastAPI', category: 'Backend & Cloud', icon: 'zap', level: 'Advanced', display_order: 1, is_visible: true, created_at: '' },
    { id: 's20', name: 'Node.js & Express', category: 'Backend & Cloud', icon: 'server', level: 'Proficient', display_order: 2, is_visible: true, created_at: '' },
    { id: 's21', name: 'Firebase & Firestore', category: 'Backend & Cloud', icon: 'flame', level: 'Advanced', display_order: 3, is_visible: true, created_at: '' },
    { id: 's22', name: 'Supabase (Postgres/Auth)', category: 'Backend & Cloud', icon: 'database', level: 'Advanced', display_order: 4, is_visible: true, created_at: '' },
    { id: 's23', name: 'Google Cloud Platform', category: 'Backend & Cloud', icon: 'cloud', level: 'Proficient', display_order: 5, is_visible: true, created_at: '' },
    { id: 's24', name: 'AWS Lambda & DynamoDB', category: 'Backend & Cloud', icon: 'cloud-lightning', level: 'Proficient', display_order: 6, is_visible: true, created_at: '' },
    { id: 's25', name: 'RESTful APIs & JWT', category: 'Backend & Cloud', icon: 'shield-check', level: 'Advanced', display_order: 7, is_visible: true, created_at: '' },

    // Databases
    { id: 's26', name: 'PostgreSQL', category: 'Databases', icon: 'database', level: 'Advanced', display_order: 1, is_visible: true, created_at: '' },
    { id: 's27', name: 'MongoDB', category: 'Databases', icon: 'hard-drive', level: 'Advanced', display_order: 2, is_visible: true, created_at: '' },
    { id: 's28', name: 'Firebase Realtime DB', category: 'Databases', icon: 'flame', level: 'Advanced', display_order: 3, is_visible: true, created_at: '' },
    { id: 's29', name: 'AWS DynamoDB', category: 'Databases', icon: 'database', level: 'Proficient', display_order: 4, is_visible: true, created_at: '' },

    // DevOps & Tools
    { id: 's30', name: 'Docker', category: 'DevOps & Tools', icon: 'box', level: 'Proficient', display_order: 1, is_visible: true, created_at: '' },
    { id: 's31', name: 'Git & GitHub', category: 'DevOps & Tools', icon: 'git-branch', level: 'Advanced', display_order: 2, is_visible: true, created_at: '' },
    { id: 's32', name: 'Wireshark', category: 'DevOps & Tools', icon: 'activity', level: 'Proficient', display_order: 3, is_visible: true, created_at: '' },
    { id: 's33', name: 'Fly.io', category: 'DevOps & Tools', icon: 'send', level: 'Proficient', display_order: 4, is_visible: true, created_at: '' },
    { id: 's34', name: 'Linux / Bash', category: 'DevOps & Tools', icon: 'terminal', level: 'Proficient', display_order: 5, is_visible: true, created_at: '' },
    { id: 's35', name: 'Postman', category: 'DevOps & Tools', icon: 'send', level: 'Advanced', display_order: 6, is_visible: true, created_at: '' },
    { id: 's36', name: 'MQTT Protocol', category: 'DevOps & Tools', icon: 'radio', level: 'Proficient', display_order: 7, is_visible: true, created_at: '' },
  ],
  experience: [
    {
      id: 'e1',
      title: 'Full Stack Developer',
      company: 'Expectation Walkers Gen AI Research and Services Pvt. Ltd.',
      company_url: 'https://expectationwalkers.com',
      description: 'Full-stack development, AI integration, and cloud deployment for generative AI products.',
      responsibilities: [
        'Developed and maintained full-stack web applications using React and modern web technologies.',
        'Integrated Firebase services and real-time databases for efficient data management and synchronization.',
        'Used Google Cloud Platform services for scalable application deployment.',
        'Integrated OpenAI technologies for conversational AI and intelligent automation.',
        'Utilized AI coding tools and prompt engineering techniques to improve development efficiency.',
        'Collaborated on debugging, testing, deployment, and feature implementation.'
      ],
      start_date: 'May 2026',
      end_date: 'Sep 2026',
      is_current: false,
      location: 'Kerala, India',
      technologies: ['React', 'TypeScript', 'Firebase', 'OpenAI APIs', 'Google Cloud Platform', 'Prompt Engineering'],
      display_order: 1,
      created_at: new Date().toISOString(),
    },
    {
      id: 'e2',
      title: 'Python Programming Intern',
      company: 'Revertech IT Solutions',
      company_url: 'https://revertech.in',
      description: 'Python programming and automated script development.',
      responsibilities: [
        'Worked on Python programming, core language concepts, and basic automation tasks.',
        'Built utility scripts and assisted in backend development modules.'
      ],
      start_date: 'Aug 2024',
      end_date: 'Sep 2024',
      is_current: false,
      location: 'Kerala, India',
      technologies: ['Python', 'Automation', 'Data Structures'],
      display_order: 2,
      created_at: new Date().toISOString(),
    },
  ],
  education: [
    {
      id: 'ed1',
      degree: 'M.Tech',
      field_of_study: 'Computer Science and Engineering (AI & Data Science)',
      institution: 'Cochin University of Science and Technology (CUSAT)',
      start_year: '2025',
      end_year: '2027',
      grade_or_status: 'Pursuing',
      location: 'Kochi, Kerala, India',
      display_order: 1,
      created_at: new Date().toISOString(),
    },
    {
      id: 'ed2',
      degree: 'B.Tech',
      field_of_study: 'Information Technology',
      institution: 'Government Engineering College Idukki (GECI)',
      start_year: '2021',
      end_year: '2025',
      grade_or_status: 'Graduated',
      location: 'Idukki, Kerala, India',
      display_order: 2,
      created_at: new Date().toISOString(),
    },
  ],
  achievements: [
    {
      id: 'a1',
      title: 'GATE 2024 Qualified',
      subtitle: 'Computer Science and Information Technology',
      date_or_year: '2024',
      description: 'Qualified the prestigious Graduate Aptitude Test in Engineering in Computer Science & Information Technology, demonstrating strong theoretical foundations in algorithms, system architecture, and computation.',
      badge: 'National Examination',
      display_order: 1,
      is_visible: true,
      created_at: new Date().toISOString(),
    },
    {
      id: 'a2',
      title: 'Best Employee of the Month',
      subtitle: 'Awarded twice at Expectation Walkers',
      date_or_year: '2026',
      description: 'Recognized twice for outstanding contributions, dedication to AI product development, fast turnaround, and proactive problem-solving.',
      badge: 'Double Recipient',
      display_order: 2,
      is_visible: true,
      created_at: new Date().toISOString(),
    },
    {
      id: 'a3',
      title: 'IEEE Best Student Volunteer Award',
      subtitle: 'IEEE RAS SBC GECI',
      date_or_year: '2023',
      description: 'Honored with the Best Student Volunteer Award for exceptional dedication, leadership in student branch activities, and community impact.',
      badge: 'Leadership Honor',
      display_order: 3,
      is_visible: true,
      created_at: new Date().toISOString(),
    },
  ],
  leadership: [
    {
      id: 'l1',
      role: 'University Union Council Coordinator',
      organization: 'CUSAT',
      period: '2025–26',
      description: 'Coordinating student activities, university-level initiatives, and student advocacy across academic faculties.',
      display_order: 1,
      is_visible: true,
      created_at: new Date().toISOString(),
    },
    {
      id: 'l2',
      role: 'Vice Chairperson',
      organization: 'IEEE RAS SBC GECI',
      period: '2023–24',
      description: 'Led robotics and automation society initiatives, workshops, technical competitions, and regional student chapters.',
      display_order: 2,
      is_visible: true,
      created_at: new Date().toISOString(),
    },
    {
      id: 'l3',
      role: 'Chairperson',
      organization: 'IEEE RAS SBC GECI',
      period: '2022–23',
      description: 'Directed all student branch chapter operations, executive team planning, tech seminars, and outreach programs.',
      display_order: 3,
      is_visible: true,
      created_at: new Date().toISOString(),
    },
    {
      id: 'l4',
      role: 'Social Media Coordinator',
      organization: 'GDSC GECI (Google Developer Student Clubs)',
      period: '2023–24',
      description: 'Managed digital engagement, technical event branding, and developer student outreach across social channels.',
      display_order: 4,
      is_visible: true,
      created_at: new Date().toISOString(),
    },
    {
      id: 'l5',
      role: 'Event Coordinator',
      organization: 'IEEE RAS SBC and NSS GECI',
      period: '2022–24',
      description: 'Organized major technical hackathons, volunteering drives, and community service camps.',
      display_order: 5,
      is_visible: true,
      created_at: new Date().toISOString(),
    },
    {
      id: 'l6',
      role: 'Oasis Pain and Palliative Dept. Representative',
      organization: 'GECI',
      period: '2022–23',
      description: 'Facilitated healthcare volunteering drives, student community service, and palliative patient care initiatives.',
      display_order: 6,
      is_visible: true,
      created_at: new Date().toISOString(),
    },
  ],
  certifications: [],
  socialLinks: [
    {
      id: 'sl1',
      platform: 'GitHub',
      url: 'https://github.com/bilalvpm4321',
      icon: 'github',
      label: 'github.com/bilalvpm4321',
      display_order: 1,
      is_visible: true,
      created_at: new Date().toISOString(),
    },
    {
      id: 'sl2',
      platform: 'LinkedIn',
      url: 'https://www.linkedin.com/in/bilalvpm4321',
      icon: 'linkedin',
      label: 'linkedin.com/in/bilalvpm4321',
      display_order: 2,
      is_visible: true,
      created_at: new Date().toISOString(),
    },
    {
      id: 'sl3',
      platform: 'Email',
      url: 'mailto:bilalvpm2@gmail.com',
      icon: 'mail',
      label: 'bilalvpm2@gmail.com',
      display_order: 3,
      is_visible: true,
      created_at: new Date().toISOString(),
    },
    {
      id: 'sl4',
      platform: 'Phone',
      url: 'tel:+917306448145',
      icon: 'phone',
      label: '+91-7306448145',
      display_order: 4,
      is_visible: true,
      created_at: new Date().toISOString(),
    },
  ],
  siteSettings: {
    general: {
      siteTitle: 'Bilal Ahamed PT | AI & Full Stack Developer',
      metaDescription: 'Official portfolio of Bilal Ahamed PT. M.Tech AI & Data Science student at CUSAT, Full Stack Developer, Generative AI & ML specialist.',
      accentColor: '#38bdf8',
      enableContactForm: true,
      enableRealtime: true,
    },
    hero: {
      badgeText: 'Available for AI & Full-Stack Roles',
      yearsExperience: '2+',
      completedProjects: '10+',
      focusArea: 'Generative AI & Scalable Web Systems',
      highlights: [
        {
          id: 'hl-1',
          icon: 'brain',
          title: 'M.Tech AI & DS',
          subtitle: 'CUSAT 2025–2027',
        },
        {
          id: 'hl-2',
          icon: 'code',
          title: 'Full Stack & GenAI',
          subtitle: 'React • Python • FastAPI',
        },
        {
          id: 'hl-3',
          icon: 'database',
          title: 'Cloud & Realtime',
          subtitle: 'GCP • AWS • Supabase',
        },
        {
          id: 'hl-4',
          icon: 'sparkles',
          title: 'GATE 2024',
          subtitle: 'CS & IT Qualified',
        },
        {
          id: 'hl-5',
          icon: 'graduation',
          title: 'B.Tech IT Graduate',
          subtitle: 'GEC Idukki 2021–2025',
        },
        {
          id: 'hl-6',
          icon: 'cpu',
          title: 'Machine Learning',
          subtitle: 'PyTorch • LangChain • RAG',
        },
      ],
    },
  },
};
